### ISSUE TITLE
Why is the Microsoft Store the only available option to download and donate?

### ISSUE THREAD

**Issue by Jonnybvb76** [RuliaReader/Rulia#86]
Hey, this is probably a strange question but as time goes by I feel like Microsoft is controlling too much and there should be some alternative download for this application since it's an offline reader. You probably need to add another updater for that devices then but I guess that's a good trade for better avaibility :) 

Are there also plans for Linux/Mac Support (primarly Linux)? And maybe an open source that people could commit on it?

**Comment by LancerComet** [comment]
This is a UWP (Universal Windows Platform) application, and for UWP programs, the Microsoft Store is currently the best distribution channel:

- The Microsoft Store provides a complete set of functionalities for distributing software (a complete dashboard, full API, etc.).
- The Microsoft Store provides a free certificate for every UWP application. This certificate would be very expensive if purchased separately and is indispensable. Without the certificate, the application would not be trusted by the Windows system, and the UWP could not be simply double-clicked to install.

As for why it is a UWP, it's because I personally want to be able to read comics on my Surface and gaming PC with comprehensive touch support, which makes UWP a suitable choice.

Theoretically, if one wanted to make the program compatible with other platforms, the first step would be to migrate the application from UWP to .NET and use frameworks like Avalonia to replace WinUI. However, this task is essentially rewriting the entire program and is not currently under consideration.

**Comment by Jonnybvb76** [comment]
Thank you for answer, I see your Point behind using microsoft as the license would be expensive (I didn't thought about that) and I use a surface too ;) (nice feature for the pen btw).

**Comment by LancerComet** [comment]
Happy reading on your Surface

![image](https://github.com/RuliaReader/Rulia/assets/10321350/04619228-cc08-45fe-9827-acec7ba21fdc)
